### ISSUE TITLE
Initialize Store with initialState

### ISSUE THREAD

**Issue by Neilpoulin** [dananw/next-with-redux-toolkit#4]
Hi, Thanks for this example repo. It's pretty helpful. However, there seems to be something missing: hydrating the store with an initial state. 

In the lib/with-redux-store.js file, there are several references to  `initializeStore(initialState)` however the function definition doesn't take any arguments, so nothing happens with the initialState. Any thoughts on how this should work with an initial state?

**Comment by dananw** [comment]
hi bro, if you want to initialState you can change it on this file
https://github.com/dananw/next-with-redux-toolkit/blob/34e19f9c03bb6837246f392275296b885a523478/store/count/countSlice.js#L4

for hydrating and persist you can create a custom function to save the last value to local-storage, if you don't want to bother you can use lib https://github.com/rt2zz/redux-persist
